package com.realestate.mapper;

import com.realestate.dto.ApartmentDTO;
import com.realestate.entity.person.Agent;
import com.realestate.entity.person.Seller;
import com.realestate.entity.property.urban.residential.Apartment;
import org.mapstruct.*;

@Mapper(componentModel = "spring")
public interface ApartmentMapper {

    @Mapping(target = "id", source = "entity.id")
    @Mapping(target = "propertyCode", source = "entity.propertyCode")
    @Mapping(target = "price", source = "entity.price")
    @Mapping(target = "address", source = "entity.address")
    @Mapping(target = "description", source = "entity.description")
    @Mapping(target = "status", source = "entity.status")
    @Mapping(target = "sellerId", source = "entity.seller.id")
    @Mapping(target = "agentId", source = "entity.agent.id")
    @Mapping(target = "orientation", source = "entity.orientation")
    @Mapping(target = "bedrooms", source = "entity.bedrooms")
    @Mapping(target = "bathrooms", source = "entity.bathrooms")
    @Mapping(target = "garageSpaces", source = "entity.garageSpaces")
    @Mapping(target = "apartmentNumber", source = "entity.apartmentNumber")
    @Mapping(target = "floor", source = "entity.floor")
    @Mapping(target = "livingRoom", source = "entity.livingRoom")
    @Mapping(target = "condominiumFee", source = "entity.condominiumFee")
    @Mapping(target = "offices", source = "entity.offices")
    @Mapping(target = "usableArea", source = "entity.usableArea")
    @Mapping(target = "privateArea", source = "entity.privateArea")
    @Mapping(target = "nameOfBuilding", source = "entity.nameOfBuilding")
    @Mapping(target = "totalArea", source = "entity.totalArea")
    @Mapping(target = "pantry", source = "entity.pantry")
    @Mapping(target = "toilet", source = "entity.toilet")
    @Mapping(target = "hasBarbecueGrill", source = "entity.hasBarbecueGrill")
    @Mapping(target = "hasSwimmingPool", source = "entity.hasSwimmingPool")
    @Mapping(target = "yearsOfConstruction", source = "entity.yearsOfConstruction")
    @Mapping(target = "hasBalcony", source = "entity.hasBalcony")
    @Mapping(target = "isRented", source = "entity.isRented")
    @Mapping(target = "isInhabited", source = "entity.isInhabited")
    @Mapping(target = "floorType", source = "entity.floorType")
    @Mapping(target = "hasAirConditioning", source = "entity.hasAirConditioning")
    @Mapping(target = "hasSurveillanceCameras", source = "entity.hasSurveillanceCameras")
    @Mapping(target = "hasCabinets", source = "entity.hasCabinets")
    @Mapping(target = "hasLaundry", source = "entity.hasLaundry")
    @Mapping(target = "sauna", source = "entity.sauna")
    @Mapping(target = "suites", source = "entity.suites")
    @Mapping(target = "bars", source = "entity.bars")
    @Mapping(target = "employeeRoom", source = "entity.employeeRoom")
    @Mapping(target = "employeeBathroom", source = "entity.employeeBathroom")
    @Mapping(target = "garagesInRow", source = "entity.garagesInRow")
    @Mapping(target = "numberOfBlocks", source = "entity.numberOfBlocks")
    @Mapping(target = "totalOfApartments", source = "entity.totalOfApartments")
    @Mapping(target = "partyHall", source = "entity.partyHall")
    @Mapping(target = "gamesRoom", source = "entity.gamesRoom")
    @Mapping(target = "playground", source = "entity.playground")
    @Mapping(target = "toyArea", source = "entity.toyArea")
    @Mapping(target = "sportsCourt", source = "entity.sportsCourt")
    @Mapping(target = "hasElectronicGate", source = "entity.hasElectronicGate")
    @Mapping(target = "electronicDoorman", source = "entity.electronicDoorman")
    @Mapping(target = "intercom", source = "entity.intercom")
    @Mapping(target = "gourmetBalcony", source = "entity.gourmetBalcony")
    @Mapping(target = "elevator", source = "entity.elevator")
    @Mapping(target = "compartment", source = "entity.compartment")
    @Mapping(target = "visitingTime", source = "entity.visitingTime")
    @Mapping(target = "exclusiveSwimmingPool", source = "entity.exclusiveSwimmingPool")
    @Mapping(target = "exclusiveSauna", source = "entity.exclusiveSauna")
    @Mapping(target = "mezzanine", source = "entity.mezzanine")
    @Mapping(target = "hasKitchen", source = "entity.hasKitchen")
    @Mapping(target = "propertyCategory", constant = "APARTMENT")
    ApartmentDTO toDto(Apartment entity);


    @Mapping(target = "propertyCode", source = "dto.propertyCode")
    @Mapping(target = "price", source = "dto.price")
    @Mapping(target = "address", source = "dto.address")
    @Mapping(target = "description", source = "dto.description")
    @Mapping(target = "status", source = "dto.status")
    @Mapping(target = "seller", source = "seller")
    @Mapping(target = "agent", source = "agent")
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "orientation", source = "dto.orientation")
    @Mapping(target = "bedrooms", source = "dto.bedrooms")
    @Mapping(target = "bathrooms", source = "dto.bathrooms")
    @Mapping(target = "garageSpaces", source = "dto.garageSpaces")
    @Mapping(target = "apartmentNumber", source = "dto.apartmentNumber")
    @Mapping(target = "floor", source = "dto.floor")
    @Mapping(target = "livingRoom", source = "dto.livingRoom")
    @Mapping(target = "condominiumFee", source = "dto.condominiumFee")
    @Mapping(target = "offices", source = "dto.offices")
    @Mapping(target = "usableArea", source = "dto.usableArea")
    @Mapping(target = "privateArea", source = "dto.privateArea")
    @Mapping(target = "nameOfBuilding", source = "dto.nameOfBuilding")
    @Mapping(target = "totalArea", source = "dto.totalArea")
    @Mapping(target = "pantry", source = "dto.pantry")
    @Mapping(target = "toilet", source = "dto.toilet")
    @Mapping(target = "hasBarbecueGrill", source = "dto.hasBarbecueGrill")
    @Mapping(target = "hasSwimmingPool", source = "dto.hasSwimmingPool")
    @Mapping(target = "yearsOfConstruction", source = "dto.yearsOfConstruction")
    @Mapping(target = "hasBalcony", source = "dto.hasBalcony")
    @Mapping(target = "isRented", source = "dto.isRented")
    @Mapping(target = "isInhabited", source = "dto.isInhabited")
    @Mapping(target = "floorType", source = "dto.floorType")
    @Mapping(target = "hasAirConditioning", source = "dto.hasAirConditioning")
    @Mapping(target = "hasSurveillanceCameras", source = "dto.hasSurveillanceCameras")
    @Mapping(target = "hasCabinets", source = "dto.hasCabinets")
    @Mapping(target = "hasLaundry", source = "dto.hasLaundry")
    @Mapping(target = "sauna", source = "dto.sauna")
    @Mapping(target = "suites", source = "dto.suites")
    @Mapping(target = "bars", source = "dto.bars")
    @Mapping(target = "employeeRoom", source = "dto.employeeRoom")
    @Mapping(target = "employeeBathroom", source = "dto.employeeBathroom")
    @Mapping(target = "garagesInRow", source = "dto.garagesInRow")
    @Mapping(target = "numberOfBlocks", source = "dto.numberOfBlocks")
    @Mapping(target = "totalOfApartments", source = "dto.totalOfApartments")
    @Mapping(target = "partyHall", source = "dto.partyHall")
    @Mapping(target = "gamesRoom", source = "dto.gamesRoom")
    @Mapping(target = "playground", source = "dto.playground")
    @Mapping(target = "toyArea", source = "dto.toyArea")
    @Mapping(target = "sportsCourt", source = "dto.sportsCourt")
    @Mapping(target = "hasElectronicGate", source = "dto.hasElectronicGate")
    @Mapping(target = "electronicDoorman", source = "dto.electronicDoorman")
    @Mapping(target = "intercom", source = "dto.intercom")
    @Mapping(target = "gourmetBalcony", source = "dto.gourmetBalcony")
    @Mapping(target = "elevator", source = "dto.elevator")
    @Mapping(target = "compartment", source = "dto.compartment")
    @Mapping(target = "visitingTime", source = "dto.visitingTime")
    @Mapping(target = "exclusiveSwimmingPool", source = "dto.exclusiveSwimmingPool")
    @Mapping(target = "exclusiveSauna", source = "dto.exclusiveSauna")
    @Mapping(target = "mezzanine", source = "dto.mezzanine")
    @Mapping(target = "hasKitchen", source = "dto.hasKitchen")
    @Mapping(target = "propertyCategory", constant = "APARTMENT")
    Apartment toEntity(ApartmentDTO dto, Seller seller, Agent agent);


    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "propertyCode", source = "dto.propertyCode")
    @Mapping(target = "price", source = "dto.price")
    @Mapping(target = "address", source = "dto.address")
    @Mapping(target = "description", source = "dto.description")
    @Mapping(target = "status", source = "dto.status")
    @Mapping(target = "seller", source = "seller")
    @Mapping(target = "agent", source = "agent")
    @Mapping(target = "id", source = "dto.id")
    @Mapping(target = "orientation", source = "dto.orientation")
    @Mapping(target = "bedrooms", source = "dto.bedrooms")
    @Mapping(target = "bathrooms", source = "dto.bathrooms")
    @Mapping(target = "garageSpaces", source = "dto.garageSpaces")
    @Mapping(target = "apartmentNumber", source = "dto.apartmentNumber")
    @Mapping(target = "floor", source = "dto.floor")
    @Mapping(target = "livingRoom", source = "dto.livingRoom")
    @Mapping(target = "condominiumFee", source = "dto.condominiumFee")
    @Mapping(target = "offices", source = "dto.offices")
    @Mapping(target = "usableArea", source = "dto.usableArea")
    @Mapping(target = "privateArea", source = "dto.privateArea")
    @Mapping(target = "nameOfBuilding", source = "dto.nameOfBuilding")
    @Mapping(target = "totalArea", source = "dto.totalArea")
    @Mapping(target = "pantry", source = "dto.pantry")
    @Mapping(target = "toilet", source = "dto.toilet")
    @Mapping(target = "hasBarbecueGrill", source = "dto.hasBarbecueGrill")
    @Mapping(target = "hasSwimmingPool", source = "dto.hasSwimmingPool")
    @Mapping(target = "yearsOfConstruction", source = "dto.yearsOfConstruction")
    @Mapping(target = "hasBalcony", source = "dto.hasBalcony")
    @Mapping(target = "isRented", source = "dto.isRented")
    @Mapping(target = "isInhabited", source = "dto.isInhabited")
    @Mapping(target = "floorType", source = "dto.floorType")
    @Mapping(target = "hasAirConditioning", source = "dto.hasAirConditioning")
    @Mapping(target = "hasSurveillanceCameras", source = "dto.hasSurveillanceCameras")
    @Mapping(target = "hasCabinets", source = "dto.hasCabinets")
    @Mapping(target = "hasLaundry", source = "dto.hasLaundry")
    @Mapping(target = "sauna", source = "dto.sauna")
    @Mapping(target = "suites", source = "dto.suites")
    @Mapping(target = "bars", source = "dto.bars")
    @Mapping(target = "employeeRoom", source = "dto.employeeRoom")
    @Mapping(target = "employeeBathroom", source = "dto.employeeBathroom")
    @Mapping(target = "garagesInRow", source = "dto.garagesInRow")
    @Mapping(target = "numberOfBlocks", source = "dto.numberOfBlocks")
    @Mapping(target = "totalOfApartments", source = "dto.totalOfApartments")
    @Mapping(target = "partyHall", source = "dto.partyHall")
    @Mapping(target = "gamesRoom", source = "dto.gamesRoom")
    @Mapping(target = "playground", source = "dto.playground")
    @Mapping(target = "toyArea", source = "dto.toyArea")
    @Mapping(target = "sportsCourt", source = "dto.sportsCourt")
    @Mapping(target = "hasElectronicGate", source = "dto.hasElectronicGate")
    @Mapping(target = "electronicDoorman", source = "dto.electronicDoorman")
    @Mapping(target = "intercom", source = "dto.intercom")
    @Mapping(target = "gourmetBalcony", source = "dto.gourmetBalcony")
    @Mapping(target = "elevator", source = "dto.elevator")
    @Mapping(target = "compartment", source = "dto.compartment")
    @Mapping(target = "visitingTime", source = "dto.visitingTime")
    @Mapping(target = "exclusiveSwimmingPool", source = "dto.exclusiveSwimmingPool")
    @Mapping(target = "exclusiveSauna", source = "dto.exclusiveSauna")
    @Mapping(target = "mezzanine", source = "dto.mezzanine")
    @Mapping(target = "hasKitchen", source = "dto.hasKitchen")
    @Mapping(target = "propertyCategory", constant = "APARTMENT")
    void updateEntity(@MappingTarget Apartment entity, ApartmentDTO dto, Seller seller, Agent agent);
}

