package com.realestate.mapper;

import com.realestate.dto.ApartmentDTO;
import com.realestate.entity.person.Agent;
import com.realestate.entity.person.Seller;
import com.realestate.entity.property.urban.residential.Apartment;
import org.mapstruct.*;

@Mapper(componentModel = "spring")
public interface ApartmentMapper {

    @Mapping(target = "id", source = "entity.id")
    @Mapping(target = "propertyCode", source = "entity.propertyCode")
    @Mapping(target = "price", source = "entity.price")
    @Mapping(target = "address", source = "entity.address")
    @Mapping(target = "description", source = "entity.description")
    @Mapping(target = "status", source = "entity.status")
    @Mapping(target = "sellerId", source = "entity.seller.id")
    @Mapping(target = "agentId", source = "entity.agent.id")
    @Mapping(target = "orientation", source = "entity.orientation")
    @Mapping(target = "bedrooms", source = "entity.bedrooms")
    @Mapping(target = "bathrooms", source = "entity.bathrooms")
    @Mapping(target = "garageSpaces", source = "entity.garageSpaces")
    @Mapping(target = "apartmentNumber", source = "entity.apartmentNumber")
    @Mapping(target = "floor", source = "entity.floor")
    @Mapping(target = "livingRoom", source = "entity.livingRoom")
    @Mapping(target = "condominiumFee", source = "entity.condominiumFee")
    @Mapping(target = "offices", source = "entity.offices")
    @Mapping(target = "usableArea", source = "entity.usableArea")
    @Mapping(target = "privateArea", source = "entity.privateArea")
    @Mapping(target = "nameOfBuilding", source = "entity.nameOfBuilding")
    @Mapping(target = "totalArea", source = "entity.totalArea")
    @Mapping(target = "hasPantry", source = "entity.hasPantry")
    @Mapping(target = "toilet", source = "entity.toilet")
    @Mapping(target = "hasBarbecueGrill", source = "entity.hasBarbecueGrill")
    @Mapping(target = "hasSwimmingPool", source = "entity.hasSwimmingPool")
    @Mapping(target = "yearsOfConstruction", source = "entity.yearsOfConstruction")
    @Mapping(target = "hasBalcony", source = "entity.hasBalcony")
    @Mapping(target = "isRented", source = "entity.isRented")
    @Mapping(target = "isInhabited", source = "entity.isInhabited")
    @Mapping(target = "floorType", source = "entity.floorType")
    @Mapping(target = "hasAirConditioning", source = "entity.hasAirConditioning")
    @Mapping(target = "hasSurveillanceCameras", source = "entity.hasSurveillanceCameras")
    @Mapping(target = "hasCabinets", source = "entity.hasCabinets")
    @Mapping(target = "hasLaundry", source = "entity.hasLaundry")
    @Mapping(target = "hasSauna", source = "entity.hasSauna")
    @Mapping(target = "suites", source = "entity.suites")
    @Mapping(target = "hasBars", source = "entity.hasBars")
    @Mapping(target = "hasEmployeeRoom", source = "entity.hasEmployeeRoom")
    @Mapping(target = "hasEmployeeBathroom", source = "entity.hasEmployeeBathroom")
    @Mapping(target = "hasGaragesInRow", source = "entity.hasGaragesInRow")
    @Mapping(target = "numberOfBlocks", source = "entity.numberOfBlocks")
    @Mapping(target = "totalOfApartments", source = "entity.totalOfApartments")
    @Mapping(target = "hasPartyHall", source = "entity.hasPartyHall")
    @Mapping(target = "hasGamesRoom", source = "entity.hasGamesRoom")
    @Mapping(target = "hasPlayground", source = "entity.hasPlayground")
    @Mapping(target = "hasToyArea", source = "entity.hasToyArea")
    @Mapping(target = "hasSportsCourt", source = "entity.hasSportsCourt")
    @Mapping(target = "hasElectronicGate", source = "entity.hasElectronicGate")
    @Mapping(target = "hasElectronicDoorman", source = "entity.hasElectronicDoorman")
    @Mapping(target = "hasIntercom", source = "entity.hasIntercom")
    @Mapping(target = "hasGourmetBalcony", source = "entity.hasGourmetBalcony")
    @Mapping(target = "elevator", source = "entity.elevator")
    @Mapping(target = "hasCompartment", source = "entity.hasCompartment")
    @Mapping(target = "visitingTime", source = "entity.visitingTime")
    @Mapping(target = "hasExclusiveSwimmingPool", source = "entity.hasExclusiveSwimmingPool")
    @Mapping(target = "hasExclusiveSauna", source = "entity.hasExclusiveSauna")
    @Mapping(target = "hasMezzanine", source = "entity.hasMezzanine")
    @Mapping(target = "hasKitchen", source = "entity.hasKitchen")
    @Mapping(target = "propertyCategory", constant = "APARTMENT")
    ApartmentDTO toDto(Apartment entity);


    @Mapping(target = "price", source = "dto.price")
    @Mapping(target = "address", source = "dto.address")
    @Mapping(target = "description", source = "dto.description")
    @Mapping(target = "status", source = "dto.status")
    @Mapping(target = "seller", source = "seller")
    @Mapping(target = "agent", source = "agent")
    @Mapping(target = "orientation", source = "dto.orientation")
    @Mapping(target = "bedrooms", source = "dto.bedrooms")
    @Mapping(target = "bathrooms", source = "dto.bathrooms")
    @Mapping(target = "garageSpaces", source = "dto.garageSpaces")
    @Mapping(target = "apartmentNumber", source = "dto.apartmentNumber")
    @Mapping(target = "floor", source = "dto.floor")
    @Mapping(target = "livingRoom", source = "dto.livingRoom")
    @Mapping(target = "condominiumFee", source = "dto.condominiumFee")
    @Mapping(target = "offices", source = "dto.offices")
    @Mapping(target = "usableArea", source = "dto.usableArea")
    @Mapping(target = "privateArea", source = "dto.privateArea")
    @Mapping(target = "nameOfBuilding", source = "dto.nameOfBuilding")
    @Mapping(target = "totalArea", source = "dto.totalArea")
    @Mapping(target = "hasPantry", source = "dto.hasPantry")
    @Mapping(target = "toilet", source = "dto.toilet")
    @Mapping(target = "hasBarbecueGrill", source = "dto.hasBarbecueGrill")
    @Mapping(target = "hasSwimmingPool", source = "dto.hasSwimmingPool")
    @Mapping(target = "yearsOfConstruction", source = "dto.yearsOfConstruction")
    @Mapping(target = "hasBalcony", source = "dto.hasBalcony")
    @Mapping(target = "isRented", source = "dto.isRented")
    @Mapping(target = "isInhabited", source = "dto.isInhabited")
    @Mapping(target = "floorType", source = "dto.floorType")
    @Mapping(target = "hasAirConditioning", source = "dto.hasAirConditioning")
    @Mapping(target = "hasSurveillanceCameras", source = "dto.hasSurveillanceCameras")
    @Mapping(target = "hasCabinets", source = "dto.hasCabinets")
    @Mapping(target = "hasLaundry", source = "dto.hasLaundry")
    @Mapping(target = "hasSauna", source = "dto.hasSauna")
    @Mapping(target = "suites", source = "dto.suites")
    @Mapping(target = "hasBars", source = "dto.hasBars")
    @Mapping(target = "hasEmployeeRoom", source = "dto.hasEmployeeRoom")
    @Mapping(target = "hasEmployeeBathroom", source = "dto.hasEmployeeBathroom")
    @Mapping(target = "hasGaragesInRow", source = "dto.hasGaragesInRow")
    @Mapping(target = "numberOfBlocks", source = "dto.numberOfBlocks")
    @Mapping(target = "totalOfApartments", source = "dto.totalOfApartments")
    @Mapping(target = "hasPartyHall", source = "dto.hasPartyHall")
    @Mapping(target = "hasGamesRoom", source = "dto.hasGamesRoom")
    @Mapping(target = "hasPlayground", source = "dto.hasPlayground")
    @Mapping(target = "hasToyArea", source = "dto.hasToyArea")
    @Mapping(target = "hasSportsCourt", source = "dto.hasSportsCourt")
    @Mapping(target = "hasElectronicGate", source = "dto.hasElectronicGate")
    @Mapping(target = "hasElectronicDoorman", source = "dto.hasElectronicDoorman")
    @Mapping(target = "hasIntercom", source = "dto.hasIntercom")
    @Mapping(target = "hasGourmetBalcony", source = "dto.hasGourmetBalcony")
    @Mapping(target = "elevator", source = "dto.elevator")
    @Mapping(target = "hasCompartment", source = "dto.hasCompartment")
    @Mapping(target = "visitingTime", source = "dto.visitingTime")
    @Mapping(target = "hasExclusiveSwimmingPool", source = "dto.hasExclusiveSwimmingPool")
    @Mapping(target = "hasExclusiveSauna", source = "dto.hasExclusiveSauna")
    @Mapping(target = "hasMezzanine", source = "dto.hasMezzanine")
    @Mapping(target = "hasKitchen", source = "dto.hasKitchen")
    @Mapping(target = "propertyCategory", constant = "APARTMENT")
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "propertyCode", ignore = true)
    Apartment toEntity(ApartmentDTO dto, Seller seller, Agent agent);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "price", source = "dto.price")
    @Mapping(target = "address", source = "dto.address")
    @Mapping(target = "description", source = "dto.description")
    @Mapping(target = "status", source = "dto.status")
    @Mapping(target = "seller", source = "seller")
    @Mapping(target = "agent", source = "agent")
    @Mapping(target = "orientation", source = "dto.orientation")
    @Mapping(target = "bedrooms", source = "dto.bedrooms")
    @Mapping(target = "bathrooms", source = "dto.bathrooms")
    @Mapping(target = "garageSpaces", source = "dto.garageSpaces")
    @Mapping(target = "apartmentNumber", source = "dto.apartmentNumber")
    @Mapping(target = "floor", source = "dto.floor")
    @Mapping(target = "livingRoom", source = "dto.livingRoom")
    @Mapping(target = "condominiumFee", source = "dto.condominiumFee")
    @Mapping(target = "offices", source = "dto.offices")
    @Mapping(target = "usableArea", source = "dto.usableArea")
    @Mapping(target = "privateArea", source = "dto.privateArea")
    @Mapping(target = "nameOfBuilding", source = "dto.nameOfBuilding")
    @Mapping(target = "totalArea", source = "dto.totalArea")
    @Mapping(target = "hasPantry", source = "dto.hasPantry")
    @Mapping(target = "toilet", source = "dto.toilet")
    @Mapping(target = "hasBarbecueGrill", source = "dto.hasBarbecueGrill")
    @Mapping(target = "hasSwimmingPool", source = "dto.hasSwimmingPool")
    @Mapping(target = "yearsOfConstruction", source = "dto.yearsOfConstruction")
    @Mapping(target = "hasBalcony", source = "dto.hasBalcony")
    @Mapping(target = "isRented", source = "dto.isRented")
    @Mapping(target = "isInhabited", source = "dto.isInhabited")
    @Mapping(target = "floorType", source = "dto.floorType")
    @Mapping(target = "hasAirConditioning", source = "dto.hasAirConditioning")
    @Mapping(target = "hasSurveillanceCameras", source = "dto.hasSurveillanceCameras")
    @Mapping(target = "hasCabinets", source = "dto.hasCabinets")
    @Mapping(target = "hasLaundry", source = "dto.hasLaundry")
    @Mapping(target = "hasSauna", source = "dto.hasSauna")
    @Mapping(target = "suites", source = "dto.suites")
    @Mapping(target = "hasBars", source = "dto.hasBars")
    @Mapping(target = "hasEmployeeRoom", source = "dto.hasEmployeeRoom")
    @Mapping(target = "hasEmployeeBathroom", source = "dto.hasEmployeeBathroom")
    @Mapping(target = "hasGaragesInRow", source = "dto.hasGaragesInRow")
    @Mapping(target = "numberOfBlocks", source = "dto.numberOfBlocks")
    @Mapping(target = "totalOfApartments", source = "dto.totalOfApartments")
    @Mapping(target = "hasPartyHall", source = "dto.hasPartyHall")
    @Mapping(target = "hasGamesRoom", source = "dto.hasGamesRoom")
    @Mapping(target = "hasPlayground", source = "dto.hasPlayground")
    @Mapping(target = "hasToyArea", source = "dto.hasToyArea")
    @Mapping(target = "hasSportsCourt", source = "dto.hasSportsCourt")
    @Mapping(target = "hasElectronicGate", source = "dto.hasElectronicGate")
    @Mapping(target = "hasElectronicDoorman", source = "dto.hasElectronicDoorman")
    @Mapping(target = "hasIntercom", source = "dto.hasIntercom")
    @Mapping(target = "hasGourmetBalcony", source = "dto.hasGourmetBalcony")
    @Mapping(target = "elevator", source = "dto.elevator")
    @Mapping(target = "hasCompartment", source = "dto.hasCompartment")
    @Mapping(target = "visitingTime", source = "dto.visitingTime")
    @Mapping(target = "hasExclusiveSwimmingPool", source = "dto.hasExclusiveSwimmingPool")
    @Mapping(target = "hasExclusiveSauna", source = "dto.hasExclusiveSauna")
    @Mapping(target = "hasMezzanine", source = "dto.hasMezzanine")
    @Mapping(target = "hasKitchen", source = "dto.hasKitchen")
    @Mapping(target = "propertyCategory", constant = "APARTMENT")
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "propertyCode", ignore = true)
    void updateEntity(@MappingTarget Apartment entity, ApartmentDTO dto, Seller seller, Agent agent);
}

